name: game_zone_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/dart_frog
  dart_frog: ^0.3.1
  # https://pub.dev/packages/dart_frog_web_socket
  dart_frog_web_socket: ^0.1.0-dev.1
  # https://pub.dev/packages/dart_jsonwebtoken
  dart_jsonwebtoken: ^2.6.2
  # https://pub.dev/packages/dartz
  dartz: ^0.10.1
  # https://pub.dev/packages/dio
  dio: ^4.0.6
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.2.0
  # https://pub.dev/packages/get_it
  get_it: ^7.2.0
  # https://pub.dev/packages/hive
  hive: ^2.2.3
  # https://pub.dev/packages/injectable
  injectable: ^2.1.0
  # https://pub.dev/packages/path
  path: ^1.8.3
  # https://pub.dev/packages/uuid
  uuid: ^3.0.7

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/freezed
  freezed: ^2.3.2
  # https://pub.dev/packages/hive_generator
  hive_generator: ^2.0.0
  # https://pub.dev/packages/injectable_generator
  injectable_generator: ^2.1.3
  # https://pub.dev/packages/json_annotation
  # json_annotation: ^4.7.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.5.4
  # https://pub.dev/packages/mocktail
  mocktail: ^0.3.0
  # https://pub.dev/packages/test
  test: ^1.19.2
  # https://pub.dev/packages/very_good_analysis
  very_good_analysis: ^3.1.0
