name: database_service
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  hive: ^2.2.3
  path: ^1.8.2

dev_dependencies:
